CSharpSolutions/FileUpload/Models/ErrorViewModel.cs
using System;

namespace FileUpload.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSharpSolutions/FileUpload/Controllers/FileUploadController.cs
using FileUpload.Models;
using FileUpload.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly IBlobStorageHelper _blobStorageHelper;
        private readonly ILogger<FileUploadController> _logger;
        private readonly IConfiguration _configuration;
        public FileUploadController(IBlobStorageHelper blobStorageHelper, ILogger<FileUploadController> logger, IConfiguration configuration)
        {
            _blobStorageHelper = blobStorageHelper;
            _logger = logger;
            _configuration = configuration;
        }
        [HttpPost("UploadFiles")]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> Post(List<IFormFile> files)
        {
            var uploadSuccess = false;
            List<string> uploadedUriList = new List<string>();
            var strorageConnection = _configuration.GetValue<string>("StorageConnectionString");
            var containerName = _configuration.GetValue<string>("ContainerName");

            foreach (var formFile in files)
            {
                using (var ms = new MemoryStream())
                {
                    _logger.LogInformation($"File Posted {formFile.FileName}");

                    formFile.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    string uploadedUri = null;
                    (uploadSuccess, uploadedUri) = await _blobStorageHelper.UploadFileToBlobStorageAsync(fileBytes, Path.GetFileName(formFile.FileName), containerName, strorageConnection);
                    if (uploadedUri != null)
                    {
                        uploadedUriList.Add(uploadedUri);
                    }

                    _logger.LogInformation($"File UploadUri {uploadedUri}");
                }
            }
            if (uploadSuccess)
                return View("UploadSuccess",uploadedUriList);
            else
                return View("UploadError");

        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

CSharpSolutions/FileUpload/Views/FileUpload/Index.cshtml
<form method="post" enctype="multipart/form-data" asp-controller="FileUpload" asp-action="Post">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload one or more files using this form:</p>
            <input type="file" name="files" multiple />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload" />
        </div>
    </div>
</form>

CSharpSolutions/FileUpload/Views/FileUpload/UploadError.cshtml
<div class="form-group">
    <div class="col-md-10">
        <p>An error has occured...</p>
        <p>
            <a asp-area="" asp-controller="FileUpload" asp-action="Index">Upload another file?</a>
        </p>
    </div>
</div>

CSharpSolutions/FileUpload/Views/FileUpload/UploadSuccess.cshtml
@model List<string>

<div class="form-group">
    <div class="col-md-10">
        <p>Success!</p>
        @foreach (var element in Model)
        {
            <p>@Html.DisplayFor(m => element)</p>
        }
        <p>
            <a asp-area="" asp-controller="FileUpload" asp-action="Index">Upload another file</a>
        </p>
    </div>
</div>

CSharpSolutions/FileUpload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FileUpload</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FileUpload</a>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - FileUpload</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>